export enum NotificationTypeEnum {
	LEARNING_PATH_VALIDATION_REQUEST = 'LEARNING_PATH_VALIDATION_REQUEST',
	LEARNING_PATH_VALIDATION_RESPONSE = 'LEARNING_PATH_VALIDATION_RESPONSE',
	AI_SENTENCE_VALIDATION_REQUEST = 'AI_SENTENCE_VALIDATION_REQUEST',
	AI_SENTENCE_VALIDATION_RESPONSE = 'AI_SENTENCE_VALIDATION_RESPONSE',
}
